version: '3.9'

services:
    db:
        profiles: ["dev"]
        image: postgres:16.2-alpine3.19
        hostname: db
        env_file:
            - db.env
        volumes:
            - ./init_postgres:/docker-entrypoint-initdb.d
            - postgres-data:/var/lib/postgresql/data
        networks:
            - twitter_clone_network
        ports:
            - "5432:5432"
        restart: always

    api:
        profiles: ["dev"]
        build:
          context: ./app/.
          dockerfile: Dockerfile
        env_file:
            - app.env
        command: uvicorn main:app --host api --port 8000
        volumes:
            - media:/media
        depends_on:
            - db
        networks:
            - twitter_clone_network
        ports:
            - 8000:8000

    db_test:
        profiles: ["test"]
        image: postgres:16.2-alpine3.19
        hostname: db_test
        env_file:
            - db_test.env
        volumes:
            - ./init_test_postgres:/docker-entrypoint-initdb.d
        networks:
            - twitter_test_network
        ports:
            - "5432:5432"
        restart: always

    api_test:
        profiles: ["test"]
        build:
          context: ./app/.
          dockerfile: Dockerfile_test
        env_file:
            - app_test.env
        command: sh -c 'python -m pytest -s -vv'
        depends_on:
            - db_test
        networks:
            - twitter_test_network
        ports:
            - 8000:8000

    server:
        profiles: ["dev"]
        build: ./server/.
        volumes:
            - media:/usr/share/nginx/html/static/images
            - ./server/static/:/usr/share/nginx/html/static
        depends_on:
            - db
            - api
        networks:
            - twitter_clone_network
        ports:
            - 80:80

networks:
    twitter_clone_network:
        driver: bridge
    twitter_test_network:
        driver: bridge

volumes:
    postgres-data:
    media:
